# Generated by Django 4.1.5 on 2023-02-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicer_name', models.CharField(max_length=100)),
                ('servicing_name', models.CharField(max_length=100)),
                ('sevicing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
