# Generated by Django 4.1.5 on 2023-01-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('product_quantity', models.PositiveIntegerField(default=0)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expecting_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remining_quantity', models.PositiveIntegerField(default=0)),
                ('quantity_update_date', models.DateField(auto_now_add=True)),
                ('remining_quantity_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='accessories.product')),
            ],
        ),
    ]
