# Generated by Django 4.1.5 on 2023-01-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='remining_quantity_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
