# Generated by Django 4.1.5 on 2023-03-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
