# Generated by Django 4.1.5 on 2023-05-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="Sale_at",
            new_name="sale_at",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="Sale_price",
            new_name="sale_price",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="Sale_quantity",
        ),
        migrations.AddField(
            model_name="sale",
            name="sale_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
