# Generated by Django 4.1.5 on 2023-05-09 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0002_rename_sale_at_sale_sale_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.ForeignKey(
                blank=True,
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accessories.model",
            ),
        ),
    ]
