# Generated by Django 4.1.5 on 2023-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_alter_product_actual_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
