# Generated by Django 4.1.5 on 2023-01-29 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_alter_product_quantity_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_update_date',
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
