# Generated by Django 4.1.5 on 2023-05-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0004_alter_product_remining_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=100),
        ),
    ]
