# Generated by Django 4.1.5 on 2023-01-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0004_remove_product_quantity_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
