# Generated by Django 4.1.5 on 2023-02-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0005_product_sold_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
