# Generated by Django 4.1.5 on 2023-05-10 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0005_remove_model_brand_product_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.AddField(
            model_name="model",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accessories.brand",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
