# Generated by Django 4.1.5 on 2023-02-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0006_product_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
