# Generated by Django 4.1.5 on 2023-02-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0007_product_actual_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_date',
        ),
    ]
