# Generated by Django 4.1.5 on 2023-05-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0007_alter_sale_sale_at'),
        ('accessories', '0008_alter_sale_sale_at'),
    ]

    operations = [
    ]
