# Generated by Django 4.1.5 on 2023-05-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0009_merge_0007_alter_sale_sale_at_0008_alter_sale_sale_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquantityhistory',
            name='added_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
