# Generated by Django 4.1.5 on 2023-05-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0010_alter_productquantityhistory_added_at'),
        ('accessories', '0012_alter_product_actual_sale_price_and_more'),
    ]

    operations = [
    ]
