# Generated by Django 4.1.5 on 2023-05-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0013_merge_20230529_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySaleProfitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField()),
                ('stock_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_quantity', models.PositiveBigIntegerField()),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
