# Generated by Django 4.1.5 on 2023-05-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In_Progress'), ('Complete', 'Complete')], default='Pending', max_length=25),
        ),
    ]
