# Generated by Django 4.1.5 on 2023-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sevicing_cost',
            field=models.DecimalField(decimal_places=2, default='enter servicing cost...', max_digits=10),
        ),
    ]
