# Generated by Django 4.1.5 on 2023-05-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_sevicing_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='servicer_name',
            field=models.CharField(default='enter your name', max_length=100),
        ),
    ]
