# Generated by Django 5.2.15 on 2026-06-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_service_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date_added', '-id']},
        ),
    ]
