# Generated by Django 5.2.15 on 2026-06-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('visitor', 'visitor'), ('developer', 'developer')], default='visitor', max_length=100),
        ),
    ]
